### ISSUE TITLE
Implement the Home Assistant CalendarEventDevice

### ISSUE THREAD

**Issue by crazyfx1** [PTST/O365-HomeAssistant#44]
**Is your feature request related to a problem? Please describe.**
The new overhaul of the integration is great and I can already receive the events. 
To use existing lovelace calendar cards, the calendar events have to be returned in a format which is the same for all home assistant calendars. Those are defined in the CalendarEventDevice (
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/calendar/__init__.py)

I would assume that's also necessary for the component to be accepted as official hass component (but that's just my opinion).

It seems like all the methods are already existing in your component, they just need to be wired up and the event converted to the standard hass event format.

For implementation hints you could also check the caldav component:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/caldav/calendar.py

**Comment by PTST** [comment]
This has been implemented in 2.1.4

**Comment by crazyfx1** [comment]
Thank you very much, it works just flawlessly, very good job!
