### ISSUE TITLE
Component tries to require re-authentication on Home Assistant restart

### ISSUE THREAD

**Issue by editter** [PTST/O365-HomeAssistant#46]
**Describe the bug**
The configurator notification seems to show up every time I restart HA.  It looks like the token JSON is being saved inside the O365 folder but when I try and load up entity no calendar information is available.  Once I go through the link account flow the calendar information is there as expected until I restart HA again.

**To Reproduce**
1. Go through the "Link O365 account" flow
2. Restart Home Assistant
3. The "Configure" notification shows up again

**Expected behavior**
The link should persist between HA restarts

**Screenshots**
N/A

**Installation method (please select one):**
- [x] HACS
- [ ] Manual Installation

**Additional context**

- [ ] Home assistant logs attached

**Comment by PTST** [comment]
Hello

That sound strange. Can you look in ".O365-token-cache/o365.token" and provide me with the values from the "scope" parameter?

Also, how do you run homeassistant? Is it in docker, directly via python, or using home assistant os (Formerly Hass.io)

**Comment by editter** [comment]
Hi,

This is what I have in the scopes property:
```json
"scope": [
  "User.Read",
  "Calendars.ReadWrite",
  "Mail.ReadWrite",
  "Mail.Send",
  "Calendars.Read"
 ]
```

I am running Home Assistant OS in a VM on Unraid.

**Comment by PTST** [comment]
You are missing some scopes, which is probably why it tries to re-authenticate on start-up. What permissions have you set up in your azure app?

**Comment by PTST** [comment]
All of these should be set up in your azure app

Calendars.ReadWrite - Read and write user calendars
Calendars.ReadWrite.Shared - Read and write user and shared calendars
offline_access - Maintain access to data you have given it access to
Users.Read - Sign in and read user profile
email - View users' email address
Mail.ReadWrite - Read and write access to user mail
Mail.ReadWrite.Shared - Read and write user and shared mail
Mail.Send - Send mail as a user
Mail.Send.Shared - Send mail on behalf of others

**Comment by PTST** [comment]
Please also note that it takes a couple of minutes for changes to the azure app to take effect.
So after adding the missing permissions, please wait 5 minutes, restart home-assistant and then re-authenticate

**Comment by editter** [comment]
I did have the calendar set up to use the read instead of read/write but as far as I could tell everything else was correct. 
I did remove the account linking from my Microsoft account and re-did the auth flow but I'm still being prompted to link my account on HA restart. 

This is what I have set up in Azure. 
![Capture](https://user-images.githubusercontent.com/4632327/74750118-d5607e00-5230-11ea-8219-0d7a79491179.PNG)

**Comment by PTST** [comment]
Do you use the alt_auth_flow or not?

With exactly the same settings i do not seem to be able to replicate this issue.
Can you please update to v2.1.5-beta4, i have added some additional log point to the scopes validation which will show up as warnings in your logs.

**Comment by editter** [comment]
Just so you know you spelled the variable wrong on line 50 **all_permissions_grated** should be **all_permissions_granted** so it is causing an error in beta4.  I fixed the issue locally just to remove that as a possibility but I still get the "All permissions granted: False" warning. 

Logs:
```
2020-02-19 08:59:11 WARNING (SyncWorker_5) [custom_components.o365.utils] All permissions granted: False
2020-02-19 08:59:15 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/o365/__init__.py", line 33, in setup
    validate_permissions()
  File "/config/custom_components/o365/utils.py", line 53, in validate_permissions
    return all_permissions_granted
NameError: name 'all_permissions_granted' is not defined
```

This is what I have for my configuration:
```yaml
o365:
  client_id: !secrets outlook_client_id
  client_secret: !secrets outlook_client_secret
```

**Comment by PTST** [comment]
Whoops, i have fixed that in the latest version. But i can´t for the life of me replicate this issue

If i change my own scopes to the same as yours and then restart i get asked to re-authenticate, and when done my scopes changes back to the correct ones
```json
 "scope": [
  "Calendars.Read",
  "Calendars.Read.Shared",
  "Calendars.ReadWrite",
  "Calendars.ReadWrite.Shared",
  "Mail.ReadWrite",
  "Mail.ReadWrite.Shared",
  "Mail.Send",
  "Mail.Send.Shared",
  "openid",
  "profile",
  "User.Read",
  "email"
 ]
```

**Comment by gdoerr** [comment]
I'm having the same issue and can confirm the same thing happens with both auth flows.

A couple of things I've noticed:

- When I use the normal auth flow, once I auth, the dialog box in HA goes to a blank popup. The button disappears and the only thing left is the close button
- Not sure it makes any difference but I had V1 installed. Any chance there are left over bits that need to be cleaned up?
- The scopes you list above don't match what the documentation asks for. openid, profile, Calendars.Read and Calendars.Read.Shared are not on the list while offline_access is missing from your comment

I'm not seeing any errors in the log from o365 and the scope in the token cache is:
  "User.Read",
  "Calendars.ReadWrite",
  "Mail.ReadWrite",
  "Mail.Send"
 
I've deleted the file several times and it always comes back the same way. Let me know if there is additional information that would help.

**Comment by PTST** [comment]
Regarding the different scopes in the file and in the Azure App, this is due to difference in naming in the underlying O365 python api and the Azure website.

One question, is this a private o365 account you are trying to link or a corporate account?

**Comment by editter** [comment]
I am using a private account.

**Comment by PTST** [comment]
okay, we have progress, i get the same error and permissions when connecting authorizing with my private o365 account instead of my corporate one. 

Now that we know the root cause, i just need to find a way to find out if this is private account and then validate the scopes accordingly. I will let you know when i have found a fix and pushed a new release

**Comment by gdoerr** [comment]
I'm using private as well. I'm glad you were able to reproduce it!

**Comment by editter** [comment]
@PTST I was wondering, what happens if you try to use the O365 features without having a scope enabled in Azure?  I assume it gives you an error on the Azure side but I don't know that for sure.

If that is the case then do you need to validate the scopes in the HA integration at all?  If I only want to use the calendar feature it would be cool to not allow access to my emails for security reasons and then if I call the email service then catch and log the permission error so the user knows.  The way the integration is setup now its an all or nothing approach.  

Just a thought, it's your code so in the end do what you think is best!

**Comment by PTST** [comment]
Actually it seems that the permissions set in the azure app is not really used for some reason. I have a test app without the email permissions, but i can still use that app to send emails through this integration. It seems that all that matters is the scopes requested through the integration

I could potentially just add a scopes parameter to the config that would allow you to explicitly set what areas of you o365 account you want to enable access for

**Comment by PTST** [comment]
For ease of use, if i am going to enable this i would probably just let you set whether it should get permissions for email, calendar or both, rather than having you set the exact permissions to request

**Comment by PTST** [comment]
Okay guys, i have pushed a beta release [v2.1.5-beta.6](https://github.com/PTST/O365-HomeAssistant/releases/tag/v2.1.5-beta.6) that works for me on both my private and corporate accounts. Please try it out and let me know 🙂

**Comment by gdoerr** [comment]
Well, so far it appears to be working for me. I'll reboot a few more times to confirm but it looks promising.

**Comment by editter** [comment]
I've restarted a couple of times and it looks like it is working as expected.  Thanks for looking into this!

As a fun side note, I did try messing with the permissions stuff and I agree that it doesn't seem to matter.  I removed the Azure permission from my [Microsoft account](https://account.live.com/consent/Manage) and it still looks like everything works as expected so cool I guess?

Thanks again!

**Comment by gdoerr** [comment]
Not working for me.

**Comment by PTST** [comment]
@gdoerr can you try and reinstall the component? For some reason I needed to do that on my last update in HACS before it actually pulled the latest files

**Comment by gdoerr** [comment]
@PTST Awesome, no more prompts. The integration created the `o365_calendars.yaml` file and the corresponding calendar state objects. The `data` attributes are empty arrays, however.

**Comment by PTST** [comment]
@gdoerr and you are sure that there is events in you calender that happens within the next 24h?

Can you please try to add the calendars to one of the calendar-cards and see if they display the events

**Comment by gdoerr** [comment]
@PTST Thanks, the data does show up on the calendar-card. I'll have to see why I can't see the event data in the `data` attribute in Developer Tools.
