### ISSUE TITLE
Log - Configuring calendars trough configuration.yaml has been deprecated

### ISSUE THREAD

**Issue by mdegat01** [PTST/O365-HomeAssistant#49]
I'm seeing this message in my log from the o365 component:
`Configuring calendars trough configuration.yaml has been deprecated, and will be removed in a future release. Please see the docs for how to proceed`

First of all, I looked in the docs and there doesn't seem to be anything that explains what exactly was deprecated and what you should do.  Since you're saying to go to the docs to figure out how to proceed please put something in the docs that specifically references this and tells me how to proceed.

Second, I _think_ I figured out what you mean by this although I'm not totally sure.  I noticed that there's now an `o365_calendars.yaml` file in my config that I don't remember adding before.  So I believe what this is telling me is to remove this part in my `configuration.yaml`:
```diff
o365:
  client_secret: "xx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  client_id: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
- calendars:
- - name: Mike work calendar
-   start_offset: -8
-   end_offset: 336
-   calendar_name: default_calendar
```
If so, please remove that part from your example for sure.  

Final point, I'm not sure deprecation is the right word here.  If you notice in my configuration above I had one calendar listed that I called 'Mike work calendar'.  At the time I wrote that this component generated one calendar entity with the id `calendar.mike_work_calendar` that shows the list of events from 8 hours ago until 14 days from now.  But thats not what I have now.  There is no `calendar.mike_work_calendar`, instead I have 3 calendar entities called `calendar.o365_calendar`, `calendar.o365_birthdays` and `calendar.o365_united_states_holidays` which all list events from now to 24 hours from now.  Which is exactly what's in this new `o365_calendars.yaml` file.

So is this option actually deprecated or just completely unsupported ? Because it seems like configuring calendars in configuration.yaml just flat out doesn't work anymore.

As an aside I actually really like your component, I was looking for this forever and am so glad I can connect to my work calendar now.  And this all isn't a big deal to me now that I think I know what is going on I just was really confused by this message.

**Comment by PTST** [comment]
Hello

If you are receiving that log message you are currently running the unsupported beta version.  

Due to it being a beta I have deliberately not updated the documentation, and will not be doing so until it's released as a final non-beta version. 

But the short story is that the calendar configuration has been moved to its own file, o365_calendars.yaml, to align this component closer with the Google Calendar integration.

**Comment by PTST** [comment]
But I will hopefully have the time to release the final version early next week 😊

**Comment by mdegat01** [comment]
Oh!  Well that makes more sense but I'm not entirely sure how I got on the beta version then.  This is what I see in my HACS right now:
![image](https://user-images.githubusercontent.com/2037026/76656676-844d5c80-6546-11ea-86e4-49d3b0645701.png)

Is 2.1.4 beta?  I thought the beta releases were labeled with beta in the release ID.

**Comment by PTST** [comment]
Well that is strange. That log should no be present in anything before v2.1.5-beta.1

This might be my fault. For a short while some of the beta version were missing the pre-release tag. 
If you reinstall v2.1.4 from HACS the warning should not appear. Or you can ignore it until I release the final version

**Comment by mdegat01** [comment]
It's all good now that I know what's going on.  I stripped out that config and tweaked the other file so its all working the way I want it to now and no errors.  Although I guess I should probably turn on beta updates to make sure I'm on the latest and not on like beta v1.  Thanks for the help!

**Comment by PTST** [comment]
Final v2.1.5 has been released and i have added a section to the documentation pertaining to the calendar configuration

[https://github.com/PTST/O365-HomeAssistant#calendar-configuration](https://github.com/PTST/O365-HomeAssistant#calendar-configuration)
