### ISSUE TITLE
This component has been blacklisted on HACS

### ISSUE THREAD

**Issue by mdegat01** [PTST/O365-HomeAssistant#55]
I really like this component and would like to keep using it but I am concerned because it was blacklisted.  The blacklist is [here](https://github.com/hacs/default/blob/master/blacklist). Would like to see it removed from the blacklist and listed in HACS again.

**Comment by PTST** [comment]
This component is not blacklisted. The repo in the blacklist is the old name for this repo, and the new one is [still available in the default list](https://github.com/hacs/default/blob/master/integration#L189)

Please see [the pull request for that change for more info](https://github.com/hacs/default/pull/200 )

**Comment by mdegat01** [comment]
Shoot, I see the name difference now.  Sorry for the confusion.
