### ISSUE TITLE
upgrade stopped working 2.16

### ISSUE THREAD

**Issue by ThisBytes5** [PTST/O365-HomeAssistant#63]
After updating to 2.16 I get the following below.
I deleted the cache token, and the calendar yaml only to have the same error after re-configuring.
Rolling back to 2.15 fixes the issue and allows the component to work, but I'd like to be able to update.

Logger: homeassistant.components.calendar
Source: custom_components/o365/calendar.py:130
Integration: Calendar (documentation, issues)
First occurred: 8:40:17 AM (1 occurrences)
Last logged: 8:40:17 AM

o365: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/o365/calendar.py", line 130, in async_update
    events = list(await hass.async_add_executor_job(self.data.o365_get_events,
NameError: name 'hass' is not defined

**Comment by PTST** [comment]
Can you please try the newly published v.2.1.7 beta? If you are using HACS to install you have to open the page for this integration and enable whosing of beta versions

**Comment by ThisBytes5** [comment]
My sensors are there, so looks like it's working with the beta

**Comment by RogerSelwyn** [comment]
This works for me, and apologies for the bug in my PR.

**Comment by unbreakmat** [comment]
had this problem also, removed the token, restarted hassio, now works buth my main agenda "Agenda" says error 400, al other calendars are created through entitys but not the Agenda?
What could i provide you to help fuxing this error?

**Comment by unbreakmat** [comment]
investigated the issue and also deltete this old file, 0365 get the agenda buth no entity is shown in hassio
![image](https://user-images.githubusercontent.com/63264046/81572519-9bbc9080-93a3-11ea-8348-baba3ec63734.png)

**Comment by unbreakmat** [comment]
i looked somwhat further, made a new agenda in my outlook account, removed the known calendars and cache token, restart, authorisation, restart and the new calendar is found, still the first agenda 'agenda' is found through known calendars yaml buth gives an response error 400

**Comment by unbreakmat** [comment]
noticed now an error in the system
![image](https://user-images.githubusercontent.com/63264046/81573623-028e7980-93a5-11ea-9192-06dfb61130d7.png)

**Comment by RogerSelwyn** [comment]
> That should be fixed by the 2.1.7 beta from what I can see above.

**Comment by unbreakmat** [comment]
meanwhile my second calendar in row stopped working also (error smae is described)
![image](https://user-images.githubusercontent.com/63264046/81625348-eb797700-93f8-11ea-90fd-97fd4adf4ec2.png)

please fix this ....

**Comment by PTST** [comment]
I have promoted this fix to a public 2.1.7 release.

@unbreakmat as pointed out by @RogerSelwyn this should also fix your issue.

**Comment by unbreakmat** [comment]
> I have promoted this fix to a public 2.1.7 release.
> 
> @unbreakmat as pointed out by @RogerSelwyn this should also fix your issue.

upgraded and found no errors in it , calendars are working , i let you know if this changes  
bu great work thanks!

**Comment by ThisBytes5** [comment]
Ditto, been working great all day. Thanks again
