### ISSUE TITLE
Enhancement: add service to update calendar

### ISSUE THREAD

**Issue by gijbelsy** [PTST/O365-HomeAssistant#71]
Is it possible to add the service: 'update calendar data'.
When calendar data is changed, I would like to have the possibility to call this service in HA to update the data.
Also after a reboot of HA, it takes some time to update the calendars automatically.

**Comment by PTST** [comment]
Home Assistant has this build in natively, just call the `homeassistant.update_entity` service on the calendar entity you want to update

**Comment by gijbelsy** [comment]
Problem is that this isn't working properly.
When HA reboots the calendar entity is empty (even there are events within the next 24Hrs).
If I issue the update_entity service the data remains empty, until midnight has passed.
Log shows no error's concerning this.
