### ISSUE TITLE
Trying to have a list of all event of the day 

### ISSUE THREAD

**Issue by thib5** [PTST/O365-HomeAssistant#75]
Hi, I'm trying to see in my GUI a list of all calendar event. ( at least the next one ) 

I know for sure that the title is able summary but I don't know how to extract that info

**Comment by PTST** [comment]
Please use something like https://github.com/atomic7777/atomic_calendar to show a calendar view in your homeassistant.

Cards and views of the data is currently outside the scope of this addon.
